GET http://localhost:5000/api/users/12

//404
GET http://localhost:5000/api/users/100


//201 {}
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName": "Roll",
    "lastName": "Rollovich",
    "email": "roll@gmail.com",
    "tel": "+380888456887"
}

//422 {}
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName": "Roll",
    "lastName": "Rollovich",
    "email": "roll@gmail.com",
    "tel": "+38098345670"
}


GET http://localhost:5000/api/users?page=2&results=5